### ISSUE TITLE
Hello, It seems we have made very similar mods

### ISSUE THREAD

**Issue by Scherso** [uku3lig/betterhurtcam#1]
Is there any way I can contact you, I want to make sure there's no conflict between us having mods of the same name, and features, but for different versions of the game.

**Comment by uku3lig** [comment]
It shouldn't be a problem, since yours seems to be for forge 1.8.9 and 1.12.2 while mine is for fabric 1.18.x

**Comment by Scherso** [comment]
thanks, just making sure, I’ll add a redirect to this mod for 1.18 users on my repo, I think it’s really cool :)
