### ISSUE TITLE
Option to only revert the damage tilt for specific sources

### ISSUE THREAD

**Issue by FrostBird347** [uku3lig/betterhurtcam#8]
While this is probably out of scope, an option to revert the damage tilt for specific types of damage (e.g old tilt for fall damage, drowning and poison but not for damage from external mobs) would be great.

**Comment by uku3lig** [comment]
while that sounds like a nice idea, it's not currently possible to do that due to how the hurtcam works, since it doesn't have access to the damage source & type. it could *maybe* be achievable, but wouldn't be easy and would probably bring a lot of technical debt to the project.
