### ISSUE TITLE
"Old" hurtcam option does not work in 1.21

### ISSUE THREAD

**Issue by iltaa** [uku3lig/betterhurtcam#9]
The "Old" tilt option doesn't do anything on 1.21. The Damage Tilt still stays yaw-based.

https://github.com/uku3lig/betterhurtcam/assets/172936789/d2c72df8-6b85-445e-8120-4a4e90ba2f1c

**Comment by uku3lig** [comment]
https://modrinth.com/mod/betterhurtcam/version/CSFEUtF2
